import { useCallback, useEffect, useState } from "react";
import { Edit, Loader2, Save, Trash2, X } from "lucide-react";
import api from "../api/api";
import getAdminCollection from "../api/getAdminCollection";

const blank={title:"",company:"",employmentType:"",location:"",startDate:"",endDate:"",isCurrent:false,description:"",technologies:"",displayOrder:1,visible:true};
export default function ManageExperiences(){
 const [items,setItems]=useState([]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
 const load=useCallback(async()=>{try{const {data,compatibilityMode}=await getAdminCollection("Experiences");setItems(Array.isArray(data)?data:[]);if(compatibilityMode)setStatus("Backend update pending; showing public experience for now.");}catch{setStatus("Could not load experience.");}},[]);
 useEffect(()=>{void load();},[load]);
 const save=async e=>{e.preventDefault();setBusy(true);try{const payload={...form,displayOrder:Number(form.displayOrder)||1,endDate:form.isCurrent?"":form.endDate};if(editing){await api.put(`/Experiences/${editing}`,payload);}else{await api.post("/Experiences",payload);}setForm(blank);setEditing(null);setStatus("Experience saved successfully.");await load();}catch{setStatus("Could not save experience.");}finally{setBusy(false)}};
 const edit=item=>{setEditing(item.id);setForm({...blank,...item});window.scrollTo({top:0,behavior:"smooth"})};
 const remove=async id=>{if(!window.confirm("Delete this experience permanently?"))return;await api.delete(`/Experiences/${id}`);await load()};
 return <div className="mx-auto max-w-5xl space-y-6 text-slate-900 dark:text-slate-100"><header className="admin-card"><p className="text-xs font-bold uppercase tracking-widest text-emerald-600">Portfolio</p><h1 className="text-3xl font-bold">Experience</h1><p className="text-sm text-slate-500">Manage real roles, dates, technologies, ordering and visibility.</p></header>{status&&<p className="admin-status">{status}</p>}<form className="admin-card" onSubmit={save}><div className="flex items-center justify-between"><h2>{editing?"Edit experience":"Add experience"}</h2>{editing&&<button type="button" className="admin-secondary" onClick={()=>{setEditing(null);setForm(blank)}}><X/> Cancel</button>}</div><div className="grid gap-4 sm:grid-cols-2">{[["title","Role"],["company","Company / organization"],["employmentType","Employment type"],["location","Location / remote"],["startDate","Start date"],["endDate","End date"],["technologies","Technologies"],["displayOrder","Display order","number"]].map(([key,label,type])=><label className="admin-label" key={key}>{label}<input className="admin-input" type={type||"text"} value={form[key]} disabled={key==="endDate"&&form.isCurrent} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><label className="admin-label">Description<textarea className="admin-input" rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="flex flex-wrap gap-4"><label className="admin-check"><input type="checkbox" checked={form.isCurrent} onChange={e=>setForm({...form,isCurrent:e.target.checked})}/>Current role</label><label className="admin-check"><input type="checkbox" checked={form.visible} onChange={e=>setForm({...form,visible:e.target.checked})}/>Visible publicly</label></div><button className="admin-primary" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<Save/>}Save experience</button></form><section className="space-y-3"><h2 className="font-bold">Saved entries ({items.length})</h2>{items.map(item=><article className="admin-list-item" key={item.id}><div className="flex-1"><div className="flex flex-wrap gap-2"><h3>{item.title}</h3>{!item.visible&&<span className="admin-badge">Hidden</span>}</div><p>{item.company} · {item.startDate} — {item.isCurrent?"Present":item.endDate}</p><small>{item.location}{item.employmentType&&` · ${item.employmentType}`}</small></div><button className="icon-button" onClick={()=>edit(item)} aria-label="Edit experience"><Edit/></button><button className="icon-button danger" onClick={()=>remove(item.id)} aria-label="Delete experience"><Trash2/></button></article>)}</section></div>
}
