import { useCallback, useEffect, useState } from "react";
import { Edit, Loader2, Save, Trash2, X } from "lucide-react";
import api from "../api/api";
import getAdminCollection from "../api/getAdminCollection";

const blank = { title:"",slug:"",description:"",longDescription:"",imageUrl:"",screenshots:"",githubUrl:"",liveUrl:"",techStack:"",featured:false,displayOrder:1,visible:true,status:"Completed",problem:"",solution:"",technicalApproach:"",keyFeatures:"",challenges:"",lessonsLearned:"" };
const textFields = [["title","Title"],["slug","Slug"],["techStack","Technologies (comma separated)"],["status","Project status"],["githubUrl","GitHub URL"],["liveUrl","Live demo URL"],["imageUrl","Cover image URL"],["screenshots","Additional screenshot URLs (one per line)"]];
const detailFields = [["description","Short description"],["longDescription","Overview / what I built"],["problem","Problem"],["solution","Solution"],["technicalApproach","Technical approach"],["keyFeatures","Key features"],["challenges","Challenges"],["lessonsLearned","What I learned"]];

export default function ManageProjects(){
  const [items,setItems]=useState([]); const [form,setForm]=useState(blank); const [editing,setEditing]=useState(null); const [busy,setBusy]=useState(false); const [status,setStatus]=useState("");
  const load=useCallback(async()=>{try{const {data,compatibilityMode}=await getAdminCollection("Projects");setItems(Array.isArray(data)?data:[]);if(compatibilityMode)setStatus("Backend update pending; showing public projects for now.");}catch{setStatus("Could not load projects.");}},[]);
  useEffect(()=>{void load();},[load]);
  const save=async(event)=>{event.preventDefault();setBusy(true);setStatus("");const payload={...form,displayOrder:Number(form.displayOrder)||1};try{if(editing){await api.put(`/Projects/${editing}`,payload);}else{await api.post("/Projects",payload);}setForm(blank);setEditing(null);setStatus("Project saved successfully.");await load();}catch{setStatus("Could not save project.");}finally{setBusy(false);}};
  const edit=(item)=>{setEditing(item.id);setForm({...blank,...item});window.scrollTo({top:0,behavior:"smooth"});};
  const remove=async(id)=>{if(!window.confirm("Delete this project permanently?"))return;await api.delete(`/Projects/${id}`);await load();};
  return <AdminPage title="Projects" subtitle="Manage portfolio cards, ordering, visibility and real case-study content." status={status}><form onSubmit={save} className="admin-card"><div className="flex items-center justify-between"><h2>{editing?"Edit project":"Add project"}</h2>{editing&&<button type="button" className="admin-secondary" onClick={()=>{setEditing(null);setForm(blank)}}><X/> Cancel</button>}</div><div className="grid gap-4 md:grid-cols-2">{textFields.map(([key,label])=><Field key={key} label={label} value={form[key]} onChange={(value)=>setForm({...form,[key]:value})}/>) }<Field label="Display order" type="number" value={form.displayOrder} onChange={(value)=>setForm({...form,displayOrder:value})}/></div>{form.imageUrl&&<img className="h-40 w-full rounded-xl object-cover" src={form.imageUrl} alt="Project cover preview"/>}{detailFields.map(([key,label])=><Field key={key} label={label} textarea value={form[key]} onChange={(value)=>setForm({...form,[key]:value})}/>)}<div className="flex flex-wrap gap-4"><Check label="Visible publicly" checked={form.visible} onChange={(value)=>setForm({...form,visible:value})}/><Check label="Featured project" checked={form.featured} onChange={(value)=>setForm({...form,featured:value})}/></div><button className="admin-primary" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<Save/>}{busy?"Saving…":"Save project"}</button></form><List items={items} edit={edit} remove={remove}/></AdminPage>;
}
function List({items,edit,remove}){return <section className="space-y-3"><h2 className="font-bold">Saved projects ({items.length})</h2>{items.map(item=><article className="admin-list-item" key={item.id}>{item.imageUrl&&<img src={item.imageUrl} alt="" className="h-20 w-28 rounded-lg object-cover"/>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3>{item.title}</h3>{item.featured&&<Badge>Featured</Badge>}{!item.visible&&<Badge>Hidden</Badge>}</div><p>{item.description}</p><small>Order {item.displayOrder} · {item.status}</small></div><div className="flex gap-2"><button className="icon-button" onClick={()=>edit(item)} aria-label="Edit project"><Edit/></button><button className="icon-button danger" onClick={()=>remove(item.id)} aria-label="Delete project"><Trash2/></button></div></article>)}</section>}
function AdminPage({title,subtitle,status,children}){return <div className="mx-auto max-w-5xl space-y-6 text-slate-900 dark:text-slate-100"><header className="admin-card"><p className="text-xs font-bold uppercase tracking-widest text-emerald-600">Portfolio</p><h1 className="text-3xl font-bold">{title}</h1><p className="text-sm text-slate-500">{subtitle}</p></header>{status&&<p role="status" className="admin-status">{status}</p>}{children}</div>}
function Field({label,value,onChange,textarea=false,type="text"}){const props={value:value??"",onChange:event=>onChange(event.target.value),className:"admin-input"};return <label className="admin-label">{label}{textarea?<textarea {...props} rows="4"/>:<input {...props} type={type}/>}</label>}
function Check({label,checked,onChange}){return <label className="admin-check"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/>{label}</label>}
function Badge({children}){return <span className="admin-badge">{children}</span>}
