import { useCallback, useEffect, useState } from "react";
import { Edit, Loader2, Save, Trash2, X } from "lucide-react";
import api from "../api/api";
import getAdminCollection from "../api/getAdminCollection";

const blank={category:"",name:"",iconUrl:"",proficiency:"",note:"",displayOrder:1,visible:true,featured:false};
export default function ManageSkills(){
  const [items,setItems]=useState([]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
  const load=useCallback(async()=>{try{const {data,compatibilityMode}=await getAdminCollection("Skills");setItems(Array.isArray(data)?data:[]);if(compatibilityMode)setStatus("Backend update pending; showing public skills for now.");}catch{setStatus("Could not load skills.");}},[]);
  useEffect(()=>{void load();},[load]);
  const save=async(e)=>{e.preventDefault();setBusy(true);try{const payload={...form,displayOrder:Number(form.displayOrder)||1};if(editing){await api.put(`/Skills/${editing}`,payload);}else{await api.post("/Skills",payload);}setForm(blank);setEditing(null);setStatus("Skill saved successfully.");await load();}catch{setStatus("Could not save skill.");}finally{setBusy(false)}};
  const edit=item=>{setEditing(item.id);setForm({...blank,...item});window.scrollTo({top:0,behavior:"smooth"})};
  const remove=async id=>{if(!window.confirm("Delete this skill permanently?"))return;await api.delete(`/Skills/${id}`);await load()};
  return <div className="mx-auto max-w-5xl space-y-6 text-slate-900 dark:text-slate-100"><header className="admin-card"><p className="text-xs font-bold uppercase tracking-widest text-emerald-600">Portfolio</p><h1 className="text-3xl font-bold">Skills</h1><p className="text-sm text-slate-500">Maintain categorized skills, proficiency labels and public visibility.</p></header>{status&&<p className="admin-status">{status}</p>}<form className="admin-card" onSubmit={save}><div className="flex items-center justify-between"><h2>{editing?"Edit skill":"Add skill"}</h2>{editing&&<button type="button" className="admin-secondary" onClick={()=>{setEditing(null);setForm(blank)}}><X/> Cancel</button>}</div><div className="grid gap-4 sm:grid-cols-2">{[["name","Skill name"],["category","Category"],["iconUrl","Icon URL"],["proficiency","Level (Experienced, Intermediate, Basics, Learning)"],["note","Optional note"],["displayOrder","Display order","number"]].map(([key,label,type])=><label className="admin-label" key={key}>{label}<input className="admin-input" type={type||"text"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="flex gap-4"><label className="admin-check"><input type="checkbox" checked={form.visible} onChange={e=>setForm({...form,visible:e.target.checked})}/>Visible publicly</label><label className="admin-check"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/>Featured</label></div><button className="admin-primary" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<Save/>}Save skill</button></form><section className="space-y-3"><h2 className="font-bold">Saved skills ({items.length})</h2>{items.map(item=><article className="admin-list-item" key={item.id}>{item.iconUrl&&<img src={item.iconUrl} alt="" className="h-10 w-10 rounded object-contain"/>}<div className="flex-1"><h3>{item.name}</h3><p>{item.category} · {item.proficiency||"No level"} · Order {item.displayOrder}</p>{item.note&&<small>{item.note}</small>}</div>{!item.visible&&<span className="admin-badge">Hidden</span>}<button className="icon-button" onClick={()=>edit(item)} aria-label="Edit skill"><Edit/></button><button className="icon-button danger" onClick={()=>remove(item.id)} aria-label="Delete skill"><Trash2/></button></article>)}</section></div>;
}
