import { useCallback, useEffect, useState } from "react";
import { Edit, Loader2, Save, Trash2, X } from "lucide-react";
import api from "../api/api";
import getAdminCollection from "../api/getAdminCollection";

const blank={degree:"",institution:"",location:"",startDate:"",endDate:"",isCurrent:false,description:"",grade:"",displayOrder:1,visible:true};
export default function ManageEducations(){
 const [items,setItems]=useState([]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
 const load=useCallback(async()=>{try{const {data,compatibilityMode}=await getAdminCollection("Educations");setItems(Array.isArray(data)?data:[]);if(compatibilityMode)setStatus("Backend update pending; showing public education for now.");}catch{setStatus("Could not load education.");}},[]);
 useEffect(()=>{void load();},[load]);
 const save=async e=>{e.preventDefault();setBusy(true);try{const payload={...form,displayOrder:Number(form.displayOrder)||1,endDate:form.isCurrent?"":form.endDate};if(editing){await api.put(`/Educations/${editing}`,payload);}else{await api.post("/Educations",payload);}setForm(blank);setEditing(null);setStatus("Education saved successfully.");await load();}catch{setStatus("Could not save education.");}finally{setBusy(false)}};
 const edit=item=>{setEditing(item.id);setForm({...blank,...item});window.scrollTo({top:0,behavior:"smooth"})};
 const remove=async id=>{if(!window.confirm("Delete this education permanently?"))return;try{await api.delete(`/Educations/${id}`);setStatus("Education deleted successfully.");await load()}catch{setStatus("Could not delete education.")}};
 return <div className="mx-auto max-w-5xl space-y-6 text-slate-900 dark:text-slate-100"><header className="admin-card"><p className="text-xs font-bold uppercase tracking-widest text-emerald-600">Portfolio</p><h1 className="text-3xl font-bold">Education</h1><p className="text-sm text-slate-500">Manage qualifications, institutions, dates, grades, ordering and visibility.</p></header>{status&&<p className="admin-status">{status}</p>}<form className="admin-card" onSubmit={save}><div className="flex items-center justify-between"><h2>{editing?"Edit education":"Add education"}</h2>{editing&&<button type="button" className="admin-secondary" onClick={()=>{setEditing(null);setForm(blank)}}><X/> Cancel</button>}</div><div className="grid gap-4 sm:grid-cols-2">{[["degree","Degree / qualification"],["institution","School / college / university"],["location","Location"],["startDate","Start date"],["endDate","End date"],["grade","Grade / CGPA (optional)"],["displayOrder","Display order","number"]].map(([key,label,type])=><label className="admin-label" key={key}>{label}<input className="admin-input" required={key==="degree"||key==="institution"} type={type||"text"} value={form[key]} disabled={key==="endDate"&&form.isCurrent} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><label className="admin-label">Description<textarea className="admin-input" rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="flex flex-wrap gap-4"><label className="admin-check"><input type="checkbox" checked={form.isCurrent} onChange={e=>setForm({...form,isCurrent:e.target.checked})}/>Currently studying</label><label className="admin-check"><input type="checkbox" checked={form.visible} onChange={e=>setForm({...form,visible:e.target.checked})}/>Visible publicly</label></div><button className="admin-primary" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<Save/>}Save education</button></form><section className="space-y-3"><h2 className="font-bold">Saved entries ({items.length})</h2>{items.map(item=><article className="admin-list-item" key={item.id}><div className="flex-1"><div className="flex flex-wrap gap-2"><h3>{item.degree}</h3>{!item.visible&&<span className="admin-badge">Hidden</span>}</div><p>{item.institution} · {item.startDate} — {item.isCurrent?"Present":item.endDate}</p><small>{item.location}{item.employmentType&&` · ${item.employmentType}`}</small></div><button className="icon-button" onClick={()=>edit(item)} aria-label="Edit education"><Edit/></button><button className="icon-button danger" onClick={()=>remove(item.id)} aria-label="Delete education"><Trash2/></button></article>)}</section></div>
}
