import { useEffect, useState } from "react";
import { Loader2, Save } from "lucide-react";
import api from "../api/api";
import { notifyProfileUpdated } from "../utils/portfolioUpdates";

const defaults = { fullName:"", role:"", shortBio:"", about:"", email:"", phone:"", location:"", githubUrl:"", linkedinUrl:"", resumeUrl:"", availabilityText:"", aboutEnabled:true, skillsEnabled:true, projectsEnabled:true, experienceEnabled:true, architectureEnabled:true, githubEnabled:true, blogEnabled:true, contactEnabled:true, contactFormEnabled:true, musicEnabled:false, testimonialsEnabled:false, exploringEnabled:true, exploringItems:"", exploringStatus:"Learning", musicHeading:"While You Browse", musicDescription:"Play some lo-fi beats and stay in the zone.", musicLabel:"Focus Mode", musicUrl:"", musicCoverUrl:"", architectureTitle:"System Design & Architecture", architectureDescription:"Designing scalable and maintainable applications.", contactTitle:"Let's Build Something Great", contactSubtitle:"Have a project, opportunity or idea? I'd be glad to hear about it." };
const fields = [
  ["fullName","Full name"],["role","Professional title"],["availabilityText","Availability badge text"],["email","Public email"],["phone","Phone"],["location","Location"],["githubUrl","GitHub URL"],["linkedinUrl","LinkedIn URL"],["resumeUrl","CV / resume URL"],
  ["architectureTitle","Architecture title"],["contactTitle","Contact title"],["contactSubtitle","Contact subtitle"],["musicHeading","Music heading"],["musicLabel","Music label"],["musicDescription","Music description"],["musicUrl","Spotify track / playlist URL"],["musicCoverUrl","Optional music cover URL"],
];
const toggles = [["aboutEnabled","About"],["skillsEnabled","Skills"],["projectsEnabled","Projects"],["experienceEnabled","Experience"],["architectureEnabled","Architecture"],["githubEnabled","GitHub"],["blogEnabled","Blog"],["contactEnabled","Contact"],["contactFormEnabled","Contact form"],["musicEnabled","Music widget"],["exploringEnabled","Currently exploring"],["testimonialsEnabled","Testimonials (reserved)"]];

export default function ProfileSettings(){
  const [profile,setProfile]=useState(defaults); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [status,setStatus]=useState("");
  useEffect(()=>{api.get("/Profile").then(({data})=>setProfile({...defaults,...data})).catch(()=>setStatus("Could not load settings.")).finally(()=>setLoading(false));},[]);
  const save=async(e)=>{e.preventDefault();setSaving(true);setStatus("");try{const {data}=await api.put("/Profile",profile);setProfile({...defaults,...data});notifyProfileUpdated();setStatus("Portfolio settings saved and published live.");}catch{setStatus("Could not save settings.");}finally{setSaving(false);}};
  if(loading)return <div className="grid min-h-[50vh] place-items-center"><Loader2 className="animate-spin text-emerald-600"/></div>;
  return <div className="mx-auto max-w-5xl space-y-6 text-slate-900 dark:text-slate-100"><div className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-slate-900"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-600">Portfolio</p><h1 className="mt-2 text-3xl font-bold">General settings</h1><p className="mt-2 text-sm text-slate-500">One source of truth for public identity, links, sections, architecture, contact and music.</p></div>
  {status&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{status}</p>}
  <form onSubmit={save} className="space-y-6">
    <section className="admin-card"><h2>Identity & links</h2><div className="grid gap-4 sm:grid-cols-2">{fields.slice(0,9).map(([key,label])=><Field key={key} label={label} value={profile[key]} onChange={(value)=>setProfile({...profile,[key]:value})}/>)}</div><Field label="Short bio" textarea value={profile.shortBio} onChange={(value)=>setProfile({...profile,shortBio:value})}/><Field label="About / engineering philosophy" textarea value={profile.about} onChange={(value)=>setProfile({...profile,about:value})}/></section>
    <section className="admin-card"><h2>Public section visibility</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{toggles.map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm dark:border-white/10"><input type="checkbox" checked={profile[key]} onChange={(e)=>setProfile({...profile,[key]:e.target.checked})}/><span>{label}</span></label>)}</div></section>
    <section className="admin-card"><h2>Architecture & contact</h2><div className="grid gap-4 sm:grid-cols-2">{fields.slice(9,12).map(([key,label])=><Field key={key} label={label} value={profile[key]} onChange={(value)=>setProfile({...profile,[key]:value})}/>)}</div><Field label="Architecture description" textarea value={profile.architectureDescription} onChange={(value)=>setProfile({...profile,architectureDescription:value})}/></section>
    <section className="admin-card"><h2>Currently exploring</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Status label" value={profile.exploringStatus} onChange={(value)=>setProfile({...profile,exploringStatus:value})}/><Field label="Learning topics (one per line)" textarea value={profile.exploringItems} onChange={(value)=>setProfile({...profile,exploringItems:value})}/></div></section>
    <section className="admin-card"><h2>While You Browse</h2><p className="mb-4 text-sm text-slate-500">Use a legitimate open.spotify.com track or playlist URL. Playback remains user initiated inside Spotify's official embed.</p><div className="grid gap-4 sm:grid-cols-2">{fields.slice(12).map(([key,label])=><Field key={key} label={label} value={profile[key]} onChange={(value)=>setProfile({...profile,[key]:value})}/>)}</div></section>
    <div className="flex justify-end"><button disabled={saving} className="button">{saving?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>} {saving?"Saving…":"Save settings"}</button></div>
  </form></div>;
}
function Field({label,value,onChange,textarea=false}){const props={value:value||"",onChange:(e)=>onChange(e.target.value),className:"w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-emerald-500 dark:border-white/10 dark:bg-slate-950 dark:text-white"};return <label className="grid gap-1.5 text-xs font-bold uppercase tracking-wide text-slate-500">{label}{textarea?<textarea {...props} rows="4"/>:<input {...props}/>}</label>;}
